version: 2
updates:
  - package-ecosystem: "npm"
    target-branch: "master"
    directory: "/"
    schedule:
      timezone: "America/Sao_Paulo"
      interval: "weekly"
      time: "23:59"
      day: "friday"
    pull-request-branch-name:
      separator: "-"
